### ISSUE TITLE
Error: pg_config executable not found.

### ISSUE THREAD

**Issue by a1exus** [kirpit/django-sample-app#5] opened 2015-10-15 03:29 UTC
I'm trying to use django-sample-app in conjunction with [dockerfiles/django-uwsgi-nginx](https://github.com/dockerfiles/django-uwsgi-nginx) and I'm getting following error:

```
Collecting psycopg2==2.6.1 (from -r /home/docker/code/app/requirements.txt (line 6))
  Downloading psycopg2-2.6.1.tar.gz (371kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-arN73d/psycopg2
The command '/bin/sh -c pip install -r /home/docker/code/app/requirements.txt' returned a non-zero code: 1
root@alexus:~/django-uwsgi-nginx# 
```

How can I resolve missing executable?

**Comment by kirpit** [comment] 2015-10-15 06:23
Your error is `Error: pg_config executable not found`, which could be because of many various reasons. It could be missing development package, not properly installed postgresql-server or simply pg_admin command is not reachable within your env path.

Since the problem is not related to this package, please do your search, ask to forums but I am closing this issue without a doubt.

**Closed as completed by kirpit** 2015-10-15 06:23 UTC

**Comment by a1exus** [comment] 2015-10-16 04:02
@kirpit I have both [PostgreSQL](https://hub.docker.com/_/postgres/), and [MySQL](https://hub.docker.com/_/mysql/) installed via Docker Hub, I guess if I to try your project without Docker, I'd probably not encounter this issue.

Is there a way to use PostgreSQL from docker container somehow?
